
[versions]
kotlin-gradle = "2.2.21"
kotlinx-coroutines = "1.10.2"
kotest-runner-junit5 = "5.9.1"
kotest-assertions-core = "5.9.1"
kotest-framework-datatest = "5.9.1"

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotest-runner-junit = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest-runner-junit5" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest-assertions-core" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest-framework-datatest" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle" }
